[package]
name = "maeptos-contract"
version = "1.0.0"
authors = []

[addresses]
ticket = "<YOUR_ADDRESS>"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
